### ISSUE TITLE
Unable to start sample - error: Error: TAR_BAD_ARCHIVE: Unrecognized archive format

### ISSUE THREAD

**Issue by NikiforovAll** [microsoft/vscode-remote-try-dotnetcore#16]
- VSCode Version: 1.48.2
- Remote OS Version: Windows_NT x64 10.0.19041
- Extension version: ms-vscode-remote.remote-containers:v0.134.1

### Error

```text
[102607 ms] Error: TAR_BAD_ARCHIVE: Unrecognized archive format
        at $.warn (c:\Users\nikiforovall\.vscode\extensions\ms-vscode-remote.remote-containers-0.134.1\dist\extension.js:1:197830)
        at $.warn (c:\Users\nikiforovall\.vscode\extensions\ms-vscode-remote.remote-containers-0.134.1\dist\extension.js:1:301454)
        at $.<anonymous> (c:\Users\nikiforovall\.vscode\extensions\ms-vscode-remote.remote-containers-0.134.1\dist\extension.js:1:165293)
        at $.emit (events.js:208:15)
        at $.[emit] (c:\Users\nikiforovall\.vscode\extensions\ms-vscode-remote.remote-containers-0.134.1\dist\extension.js:1:167753)
        at $.[maybeEnd] (c:\Users\nikiforovall\.vscode\extensions\ms-vscode-remote.remote-containers-0.134.1\dist\extension.js:1:169342)
        at $.[consumeChunk] (c:\Users\nikiforovall\.vscode\extensions\ms-vscode-remote.remote-containers-0.134.1\dist\extension.js:1:169605)
        at $.write (c:\Users\nikiforovall\.vscode\extensions\ms-vscode-remote.remote-containers-0.134.1\dist\extension.js:1:168850)
        at $.end (c:\Users\nikiforovall\.vscode\extensions\ms-vscode-remote.remote-containers-0.134.1\dist\extension.js:1:170030)
        at Socket.onend (_stream_readable.js:682:10)
        at Object.onceWrapper (events.js:291:20)
        at Socket.emit (events.js:208:15)
        at endReadableNT (_stream_readable.js:1168:12)
        at processTicksAndRejections (internal/process/task_queues.js:77:11)
```

**Comment by NikiforovAll** [comment]
I re-opened vscode completely. And now it works. Both: running from example and .devcontainer.json

**Comment by NikiforovAll** [comment]
<details><summary>.devcontainer</summary>
// For format details, see https://aka.ms/vscode-remote/devcontainer.json or this file's README at:
// https://github.com/microsoft/vscode-dev-containers/tree/v0.134.0/containers/dotnetcore
{
	"name": "Exercism development environnement",
	"build": {
		"dockerfile": "Dockerfile",
		"args": { 
			// Update 'VARIANT' to pick a .NET Core version: 2.1-bionic, 3.1-bionic
			"VARIANT": "3.1-bionic"
		}
	},

	// Set *default* container specific settings.json values on container create.
	"settings": {
		"terminal.integrated.shell.linux": "/bin/bash"
	},

	// Add the IDs of extensions you want installed when the container is created.
	"extensions": [
		"formulahendry.dotnet-test-explorer",
		"ms-dotnettools.csharp"
	],

	// Use 'forwardPorts' to make a list of ports inside the container available locally.
	"forwardPorts": [5000, 5001],

    // Next, after running the command above, uncomment lines in the 'mounts' and 'remoteEnv' lines below,
	// and open / rebuild the container so the settings take effect.
	//
	"mounts": [
		// "source=${env:HOME}${env:USERPROFILE}/.aspnet/https,target=/home/vscode/.aspnet/https,type=bind"
	],
	"remoteEnv": {
	},

	// Use 'postCreateCommand' to run commands after the container is created.
	// "postCreateCommand": "dotnet restore",

	// Comment this out to connect as a root instead.
	"remoteUser": "vscode"
}

</details>
